version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: otp-redis
    ports:
      - "6379:6379"

  otp-service:
    build: .
    container_name: otp-service
    depends_on:
      - redis
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379